CREATE TABLE USUARIO (
    USERID NVARCHAR(256) PRIMARY KEY,
    NAMEUSER VARCHAR(100),
    EMAIL NVARCHAR(100),
    WEBPASSWORD NVARCHAR(256) --senha com hash
);

CREATE TABLE CARTAO(
    NUMBERID INT PRIMARY KEY    ,
    ENDVALIDITY DATE,
    OWNERCARD VARCHAR(50),
    FLAGTYPE INT,
    LIMITTOSPEND DECIMAL(10, 2),
    SAVING DECIMAL(10, 2),
    PAYMENTYPE INT
);

CREATE TABLE CARTEIRA(
    WALLETID INT PRIMARY KEY,
    BALANCEWALLET DECIMAL(10, 2),
    BALANCEWALLETLIMIT DECIMAL(10, 2),
);

CREATE TABLE OPERACAO(
    OPERATIONID INT PRIMARY KEY,
    VALUEOPERATION DECIMAL(10, 2),
    ACTIONOPERATION DATE,
    TYPEOPERATION INT,
    ORIGNOPERATION INT,
    DESTINYOPERATION INT
);

CREATE TABLE POUPANCA(
    CARDID INT, -- FK DE NUMBERID CARTAO
    SAVINGID INT,
    SAVINGBALANCE DECIMAL(10, 2) FOREIGN KEY (CARDID) REFERENCES CARTAO(NUMBERID),
);

CREATE TABLE TAG(
    TAGID INT PRIMARY KEY,
    NAMETAG VARCHAR,
    COLOR VARCHAR
);

CREATE TABLE PRODUTO(
    CARDID INT, --FK DE NUMBERID CARTAO
    TAGID INT, --FK DE TAGID TAG
    PRODUCTID INT,
    PRODUCTNAME VARCHAR,
    PRODUCTACSITION DATE,
    PRODUCTVALUE DECIMAL(10, 2),
    PAYMENTFORM INT FOREIGN KEY (CARDID) REFERENCES CARTAO(NUMBERID),
    FOREIGN KEY (TAGID) REFERENCES TAG(TAGID),
);

CREATE TABLE CARTAOMANAGER(
    CARTAOMANAGERID INT PRIMARY KEY,
    VALORCONTROLE DECIMAL(10, 2),
    ADICIONARCARTAO INT,
    REMOVERCARTAO INT,
    REGISTARDESPESAS INT,
    REGISTRARRECEITA INT,
    REGISTRARTRANSFERENCIA INT,
    GERARPLANILHA BIT
);